version: '3.5'

services:
  streamlit:
    build: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "8501:8501"
    volumes:
      - "./project:/usr/src/app/project:delegated"
    depends_on:
      - postgres
      
  postgres:
    container_name: postgres-salinas
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  streamlit:
