salinas_app:
  target: local
  outputs:
    docker:
      type: postgres
      host: "host.docker.internal"
      user: "postgres"
      password: "postgres"
      port: 5432
      dbname: "salinas_db"
      schema : "public"
      threads: 4
    local:
      type: postgres
      host: "localhost"
      user: "postgres"
      password: "postgres"
      port: 5432
      dbname: "salinas_db"
      schema : "public"
      threads: 4